package vn.aptech.MantechHelpdesk.entities;
// Generated Oct 16, 2014 2:59:49 PM by Hibernate Tools 3.6.0


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Faq generated by hbm2java
 */
@Entity
@Table(name="Faq"
    ,schema="dbo"
    ,catalog="MantechHelpdesks"
)
public class Faq  implements java.io.Serializable {


     private int id;
     private String question;
     private String answer;

    public Faq() {
    }

	
    public Faq(int id) {
        this.id = id;
    }
    public Faq(int id, String question, String answer) {
       this.id = id;
       this.question = question;
       this.answer = answer;
    }
   
     @Id 

    
    @Column(name="Id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="Question")
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }

    
    @Column(name="Answer")
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }




}


