package vn.aptech.MantechHelpdesk.entities;
// Generated Oct 4, 2014 4:48:05 PM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Feedback generated by hbm2java
 */
@Entity
@Table(name="Feedback"
    ,schema="dbo"
    ,catalog="MantechHelpdesks"
)
public class Feedback  implements java.io.Serializable {


     private int id;
     private Complaint complaint;
     private Admin admin;
     private Member member;
     private Date dateFeedback;
     private String contents;

    public Feedback() {
    }

	
    public Feedback(int id) {
        this.id = id;
    }
    public Feedback(int id, Complaint complaint, Admin admin, Member member, Date dateFeedback, String contents) {
       this.id = id;
       this.complaint = complaint;
       this.admin = admin;
       this.member = member;
       this.dateFeedback = dateFeedback;
       this.contents = contents;
    }
   
     @Id 

    
    @Column(name="Id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_complaint")
    public Complaint getComplaint() {
        return this.complaint;
    }
    
    public void setComplaint(Complaint complaint) {
        this.complaint = complaint;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_admin")
    public Admin getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_user")
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Date_feedback", length=23)
    public Date getDateFeedback() {
        return this.dateFeedback;
    }
    
    public void setDateFeedback(Date dateFeedback) {
        this.dateFeedback = dateFeedback;
    }

    
    @Column(name="Contents")
    public String getContents() {
        return this.contents;
    }
    
    public void setContents(String contents) {
        this.contents = contents;
    }




}


