package vn.aptech.MantechHelpdesk.entities;
// Generated Oct 7, 2014 4:39:05 PM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Post generated by hbm2java
 */
@Entity
@Table(name="Post"
    ,schema="dbo"
    ,catalog="MantechHelpdesks"
)
public class Post  implements java.io.Serializable {


     private int id;
     private String title;
     private Date datePost;
     private String contents;

    public Post() {
    }

	
    public Post(int id) {
        this.id = id;
    }
    public Post(int id, String title, Date datePost, String contents) {
       this.id = id;
       this.title = title;
       this.datePost = datePost;
       this.contents = contents;
    }
   
     @Id 

    
    @Column(name="Id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="Title")
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Date_post", length=23)
    public Date getDatePost() {
        return this.datePost;
    }
    
    public void setDatePost(Date datePost) {
        this.datePost = datePost;
    }

    
    @Column(name="Contents")
    public String getContents() {
        return this.contents;
    }
    
    public void setContents(String contents) {
        this.contents = contents;
    }




}


