package vn.aptech.MantechHelpdesk.entities;
// Generated Oct 16, 2014 2:59:49 PM by Hibernate Tools 3.6.0


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Post generated by hbm2java
 */
@Entity
@Table(name="Post"
    ,schema="dbo"
    ,catalog="MantechHelpdesks"
)
public class Post  implements java.io.Serializable {


     private int id;
     private Serializable title;
     private Serializable datePost;
     private Serializable contents;

    public Post() {
    }

	
    public Post(int id) {
        this.id = id;
    }
    public Post(int id, Serializable title, Serializable datePost, Serializable contents) {
       this.id = id;
       this.title = title;
       this.datePost = datePost;
       this.contents = contents;
    }
   
     @Id 

    
    @Column(name="Id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="Title")
    public Serializable getTitle() {
        return this.title;
    }
    
    public void setTitle(Serializable title) {
        this.title = title;
    }

    
    @Column(name="Date_post")
    public Serializable getDatePost() {
        return this.datePost;
    }
    
    public void setDatePost(Serializable datePost) {
        this.datePost = datePost;
    }

    
    @Column(name="Contents")
    public Serializable getContents() {
        return this.contents;
    }
    
    public void setContents(Serializable contents) {
        this.contents = contents;
    }




}


