package DTO_Mantech_Helpdesk;
// Generated Oct 2, 2014 4:41:18 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Complaint generated by hbm2java
 */
@Entity
@Table(name="Complaint"
    ,schema="dbo"
    ,catalog="MantechHelpdesk"
)
public class Complaint  implements java.io.Serializable {


     private int id;
     private Member memberByIdUser;
     private Member memberByIdTechnician;
     private Serializable title;
     private Serializable contents;
     private Serializable status;
     private Set feedbacks = new HashSet(0);

    public Complaint() {
    }

	
    public Complaint(int id) {
        this.id = id;
    }
    public Complaint(int id, Member memberByIdUser, Member memberByIdTechnician, Serializable title, Serializable contents, Serializable status, Set feedbacks) {
       this.id = id;
       this.memberByIdUser = memberByIdUser;
       this.memberByIdTechnician = memberByIdTechnician;
       this.title = title;
       this.contents = contents;
       this.status = status;
       this.feedbacks = feedbacks;
    }
   
     @Id 

    
    @Column(name="Id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_user")
    public Member getMemberByIdUser() {
        return this.memberByIdUser;
    }
    
    public void setMemberByIdUser(Member memberByIdUser) {
        this.memberByIdUser = memberByIdUser;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_technician")
    public Member getMemberByIdTechnician() {
        return this.memberByIdTechnician;
    }
    
    public void setMemberByIdTechnician(Member memberByIdTechnician) {
        this.memberByIdTechnician = memberByIdTechnician;
    }

    
    @Column(name="Title")
    public Serializable getTitle() {
        return this.title;
    }
    
    public void setTitle(Serializable title) {
        this.title = title;
    }

    
    @Column(name="Contents")
    public Serializable getContents() {
        return this.contents;
    }
    
    public void setContents(Serializable contents) {
        this.contents = contents;
    }

    
    @Column(name="Status")
    public Serializable getStatus() {
        return this.status;
    }
    
    public void setStatus(Serializable status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="complaint")
    public Set getFeedbacks() {
        return this.feedbacks;
    }
    
    public void setFeedbacks(Set feedbacks) {
        this.feedbacks = feedbacks;
    }




}


