package DTO_Mantech_Helpdesk;
// Generated Oct 2, 2014 4:41:18 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name="Department"
    ,schema="dbo"
    ,catalog="MantechHelpdesk"
)
public class Department  implements java.io.Serializable {


     private int idDep;
     private Serializable depName;
     private Set members = new HashSet(0);

    public Department() {
    }

	
    public Department(int idDep) {
        this.idDep = idDep;
    }
    public Department(int idDep, Serializable depName, Set members) {
       this.idDep = idDep;
       this.depName = depName;
       this.members = members;
    }
   
     @Id 

    
    @Column(name="IdDep", unique=true, nullable=false)
    public int getIdDep() {
        return this.idDep;
    }
    
    public void setIdDep(int idDep) {
        this.idDep = idDep;
    }

    
    @Column(name="DepName")
    public Serializable getDepName() {
        return this.depName;
    }
    
    public void setDepName(Serializable depName) {
        this.depName = depName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="department")
    public Set getMembers() {
        return this.members;
    }
    
    public void setMembers(Set members) {
        this.members = members;
    }




}


