package DTO_Mantech_Helpdesk;
// Generated Oct 2, 2014 4:41:18 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Faq generated by hbm2java
 */
@Entity
@Table(name="Faq"
    ,schema="dbo"
    ,catalog="MantechHelpdesk"
)
public class Faq  implements java.io.Serializable {


     private int id;
     private Serializable question;
     private Serializable answer;

    public Faq() {
    }

	
    public Faq(int id) {
        this.id = id;
    }
    public Faq(int id, Serializable question, Serializable answer) {
       this.id = id;
       this.question = question;
       this.answer = answer;
    }
   
     @Id 

    
    @Column(name="Id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="Question")
    public Serializable getQuestion() {
        return this.question;
    }
    
    public void setQuestion(Serializable question) {
        this.question = question;
    }

    
    @Column(name="Answer")
    public Serializable getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(Serializable answer) {
        this.answer = answer;
    }




}


