package DTO_Mantech_Helpdesk;
// Generated Oct 2, 2014 4:41:18 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Feedback generated by hbm2java
 */
@Entity
@Table(name="Feedback"
    ,schema="dbo"
    ,catalog="MantechHelpdesk"
)
public class Feedback  implements java.io.Serializable {


     private int id;
     private Complaint complaint;
     private Member member;
     private Integer idAdmin;
     private Date dateFeedback;
     private Serializable contents;

    public Feedback() {
    }

	
    public Feedback(int id) {
        this.id = id;
    }
    public Feedback(int id, Complaint complaint, Member member, Integer idAdmin, Date dateFeedback, Serializable contents) {
       this.id = id;
       this.complaint = complaint;
       this.member = member;
       this.idAdmin = idAdmin;
       this.dateFeedback = dateFeedback;
       this.contents = contents;
    }
   
     @Id 

    
    @Column(name="Id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_complaint")
    public Complaint getComplaint() {
        return this.complaint;
    }
    
    public void setComplaint(Complaint complaint) {
        this.complaint = complaint;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_user")
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }

    
    @Column(name="Id_admin")
    public Integer getIdAdmin() {
        return this.idAdmin;
    }
    
    public void setIdAdmin(Integer idAdmin) {
        this.idAdmin = idAdmin;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Date_feedback", length=23)
    public Date getDateFeedback() {
        return this.dateFeedback;
    }
    
    public void setDateFeedback(Date dateFeedback) {
        this.dateFeedback = dateFeedback;
    }

    
    @Column(name="Contents")
    public Serializable getContents() {
        return this.contents;
    }
    
    public void setContents(Serializable contents) {
        this.contents = contents;
    }




}


