package DTO_Mantech_Helpdesk;
// Generated Oct 2, 2014 4:41:18 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Member generated by hbm2java
 */
@Entity
@Table(name="Member"
    ,schema="dbo"
    ,catalog="MantechHelpdesk"
)
public class Member  implements java.io.Serializable {


     private int id;
     private Department department;
     private Serializable username;
     private Serializable password;
     private Serializable email;
     private Serializable fullname;
     private Date birthday;
     private Serializable address;
     private Serializable sex;
     private Serializable phone;
     private Serializable avatar;
     private Serializable role;
     private Set feedbacks = new HashSet(0);
     private Set complaintsForIdUser = new HashSet(0);
     private Set complaintsForIdTechnician = new HashSet(0);

    public Member() {
    }

	
    public Member(int id) {
        this.id = id;
    }
    public Member(int id, Department department, Serializable username, Serializable password, Serializable email, Serializable fullname, Date birthday, Serializable address, Serializable sex, Serializable phone, Serializable avatar, Serializable role, Set feedbacks, Set complaintsForIdUser, Set complaintsForIdTechnician) {
       this.id = id;
       this.department = department;
       this.username = username;
       this.password = password;
       this.email = email;
       this.fullname = fullname;
       this.birthday = birthday;
       this.address = address;
       this.sex = sex;
       this.phone = phone;
       this.avatar = avatar;
       this.role = role;
       this.feedbacks = feedbacks;
       this.complaintsForIdUser = complaintsForIdUser;
       this.complaintsForIdTechnician = complaintsForIdTechnician;
    }
   
     @Id 

    
    @Column(name="Id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdDep")
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }

    
    @Column(name="Username")
    public Serializable getUsername() {
        return this.username;
    }
    
    public void setUsername(Serializable username) {
        this.username = username;
    }

    
    @Column(name="Password")
    public Serializable getPassword() {
        return this.password;
    }
    
    public void setPassword(Serializable password) {
        this.password = password;
    }

    
    @Column(name="Email")
    public Serializable getEmail() {
        return this.email;
    }
    
    public void setEmail(Serializable email) {
        this.email = email;
    }

    
    @Column(name="Fullname")
    public Serializable getFullname() {
        return this.fullname;
    }
    
    public void setFullname(Serializable fullname) {
        this.fullname = fullname;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Birthday", length=23)
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    
    @Column(name="Address")
    public Serializable getAddress() {
        return this.address;
    }
    
    public void setAddress(Serializable address) {
        this.address = address;
    }

    
    @Column(name="Sex")
    public Serializable getSex() {
        return this.sex;
    }
    
    public void setSex(Serializable sex) {
        this.sex = sex;
    }

    
    @Column(name="Phone")
    public Serializable getPhone() {
        return this.phone;
    }
    
    public void setPhone(Serializable phone) {
        this.phone = phone;
    }

    
    @Column(name="Avatar")
    public Serializable getAvatar() {
        return this.avatar;
    }
    
    public void setAvatar(Serializable avatar) {
        this.avatar = avatar;
    }

    
    @Column(name="Role")
    public Serializable getRole() {
        return this.role;
    }
    
    public void setRole(Serializable role) {
        this.role = role;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="member")
    public Set getFeedbacks() {
        return this.feedbacks;
    }
    
    public void setFeedbacks(Set feedbacks) {
        this.feedbacks = feedbacks;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="memberByIdUser")
    public Set getComplaintsForIdUser() {
        return this.complaintsForIdUser;
    }
    
    public void setComplaintsForIdUser(Set complaintsForIdUser) {
        this.complaintsForIdUser = complaintsForIdUser;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="memberByIdTechnician")
    public Set getComplaintsForIdTechnician() {
        return this.complaintsForIdTechnician;
    }
    
    public void setComplaintsForIdTechnician(Set complaintsForIdTechnician) {
        this.complaintsForIdTechnician = complaintsForIdTechnician;
    }




}


