package DTO_Mantech_Helpdesk;
// Generated Oct 2, 2014 4:41:18 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Post generated by hbm2java
 */
@Entity
@Table(name="Post"
    ,schema="dbo"
    ,catalog="MantechHelpdesk"
)
public class Post  implements java.io.Serializable {


     private int id;
     private Serializable title;
     private Date datePost;
     private Serializable contents;

    public Post() {
    }

	
    public Post(int id) {
        this.id = id;
    }
    public Post(int id, Serializable title, Date datePost, Serializable contents) {
       this.id = id;
       this.title = title;
       this.datePost = datePost;
       this.contents = contents;
    }
   
     @Id 

    
    @Column(name="Id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="Title")
    public Serializable getTitle() {
        return this.title;
    }
    
    public void setTitle(Serializable title) {
        this.title = title;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Date_post", length=23)
    public Date getDatePost() {
        return this.datePost;
    }
    
    public void setDatePost(Date datePost) {
        this.datePost = datePost;
    }

    
    @Column(name="Contents")
    public Serializable getContents() {
        return this.contents;
    }
    
    public void setContents(Serializable contents) {
        this.contents = contents;
    }




}


